# Generated by Django 4.0.2 on 2022-03-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_App', '0002_remove_doctor_acc_remove_patient_acc_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Doc_App.doctor'),
        ),
    ]
