# Generated by Django 4.0.2 on 2022-04-27 16:53

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_App', '0005_appointment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='end_hour',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=13),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_hour',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
