# Generated by Django 4.0.2 on 2022-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_App', '0006_doctor_end_hour_doctor_schedule_doctor_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
