# Generated by Django 4.0.2 on 2022-05-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_App', '0007_appointment_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canceled_by_doc',
            field=models.BooleanField(default=False),
        ),
    ]
